### ISSUE TITLE
Build and deploy kernel with CircleCI to packagecloud

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/rpi-kernel#22]
Did we any deployment to package cloud with CircleCI yet?

As the  `circle.yml` only deploys on tagged builds with `vx.x.x` I think we uploaded the kernel manually to packagecloud in the past.

```
deployment:
  release:
    tag: /v[0-9]+(\.[0-9]+)*/
    commands:
      - package_cloud push hypriot-uploader/rpi/debian/jessie $CIRCLE_ARTIFACTS/*.deb
```

The circle.yml has a deployment section, but this has to be updated to make it work.

* remove old kernel packages from packagecloud
  * See `package_cloud yank` - https://packagecloud.io/docs#yank_pkg
* upload new kernel packages to packagecloud
